name: KMLSD
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pip:
      - numpy==1.26.4
      - pandas==1.5.3
      - scipy==1.10.1
      - scikit-learn==1.7.2
      - transformers==4.29.2
      - tokenizers==0.13.3
      - peft==0.4.0
      - accelerate==1.8.1
      - safetensors==0.5.3
      - huggingface-hub==0.33.1
